apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
      - name: my-api
        image: barathg25/html
        ports:
        - containerPort: 80
        volumeMounts:
        - name: local-persistent-storage
          mountPath: /home/ubuntu
      volumes:
      - name: local-persistent-storage
        persistentVolumeClaim:
          claimName: test-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: my-api
spec:
  selector:
    app: my-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
