apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-test
  template:
    metadata:
      labels:
        app: my-test
    spec:
      containers:
      - name: my-test
        image: barathg25/pet-front
        ports:
        - containerPort: 8080

---


apiVersion: v1
kind: Service
metadata:
  name: my-test
spec:
  type: NodePort
  selector:
    app: my-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 31000
