apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-back
  template:
    metadata:
      labels:
        app: pet-back
    spec:
      containers:
      - name: pet-backend
        image: barathg25/pet-backend
        ports:
        - containerPort: 9966
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  selector:
    app: pet-back
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 9966
    nodePort: 31000
